//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPremPar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public string ID { get; set; }
        public string Vendor { get; set; }
        public string Brand { get; set; }
        public string AssetType { get; set; }
        public string ClickURL { get; set; }
        public string Notes { get; set; }
    }
}
