//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPremPar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public System.Guid ID { get; set; }
        public string AssetType { get; set; }
        public string ClickURL { get; set; }
        public string UserLog { get; set; }
        public Nullable<System.DateTime> StartDT { get; set; }
        public string BrandName { get; set; }
        public string CopyHL { get; set; }
        public string CopyBody { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public string FileName { get; set; }
    }
}
